import { cookies } from 'next/headers';

const CSRF_COOKIE_NAME = 'csrf-token';
const CSRF_HEADER_NAME = 'x-csrf-token';

/**
 * Generate a new CSRF token via API route
 * 
 * IMPORTANT: In Next.js 16+, cookies can only be modified in Route Handlers or Server Actions.
 * This function calls the /api/csrf/generate endpoint to set the cookie.
 * 
 * Use this in Server Actions or when you need to explicitly generate a new token.
 */
export async function generateCSRFToken(): Promise<string> {
  // Call the API route to generate and set the cookie
  // ✅ PRODUCTION FIX: Use relative path (works in all environments)
  const response = await fetch('/api/csrf/generate', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error('Failed to generate CSRF token');
  }

  const data = await response.json();
  return data.token;
}

/**
 * Verify that the provided CSRF token matches the one in cookies
 * ✅ ENHANCED: Now uses timing-safe comparison to prevent timing attacks
 * 
 * Use this in Server Actions to prevent CSRF attacks
 */
export async function verifyCSRFToken(token: string | undefined): Promise<boolean> {
  if (!token) {
    if (process.env.NODE_ENV === 'development') {
      console.warn('[CSRF] Token validation failed: No token provided');
    }
    return false;
  }

  const cookieStore = await cookies();
  const storedToken = cookieStore.get(CSRF_COOKIE_NAME)?.value;

  if (!storedToken) {
    if (process.env.NODE_ENV === 'development') {
      console.warn('[CSRF] Token validation failed: No stored token in cookies');
    }
    return false;
  }

  // ✅ SECURITY: Timing-safe comparison to prevent timing attacks (Phase 1)
  try {
    // Import timing-safe comparison from Node.js crypto
    const { timingSafeEqual } = await import('crypto');

    const tokenBuffer = Buffer.from(token, 'utf-8');
    const storedBuffer = Buffer.from(storedToken, 'utf-8');

    // Early length check (constant time)
    if (tokenBuffer.length !== storedBuffer.length) {
      if (process.env.NODE_ENV === 'development') {
        console.warn('[CSRF] Token validation failed: Length mismatch');
      }
      return false;
    }

    // ✅ Timing-safe comparison prevents timing attack vulnerabilities
    const isValid = timingSafeEqual(tokenBuffer, storedBuffer);

    if (!isValid && process.env.NODE_ENV === 'development') {
      console.warn('[CSRF] Token validation failed: Token mismatch');
    }

    return isValid;
  } catch (error) {
    console.error('[CSRF] Token validation error:', error);
    return false;
  }
}

/**
 * Get the current CSRF token from cookies (READ-ONLY)
 * 
 * ✅ COMPLETELY READ-ONLY - Safe for Server Components
 * 
 * The token MUST be generated by middleware.ts BEFORE this runs.
 * This function only reads the cookie, it NEVER modifies it.
 */
export async function getCSRFToken(): Promise<string | null> {
  try {
    const cookieStore = await cookies();
    const token = cookieStore.get(CSRF_COOKIE_NAME)?.value;

    if (!token) {
      console.warn('⚠️ No CSRF token found in cookies. Middleware should generate it.');
      return null;
    }

    if (process.env.NODE_ENV === 'development') {
      console.log('✅ Read CSRF token from cookie:', token.substring(0, 10) + '...');
    }

    return token;
  } catch (error) {
    console.error('Error reading CSRF token:', error);
    return null;
  }
}

/**
 * ✅ PHASE 2: Rotate CSRF token (generate new one)
 * Call after sensitive operations like password change
 */
export async function rotateCSRFToken(): Promise<string> {
  try {
    // ✅ PRODUCTION FIX: Use relative path (works in all environments)
    const response = await fetch('/api/csrf/generate', {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Content-Type': 'application/json'
      }
    });

    if (!response.ok) {
      throw new Error('Failed to rotate CSRF token');
    }

    const data = await response.json();

    if (process.env.NODE_ENV === 'development') {
      console.log('[CSRF] Token rotated successfully');
    }

    return data.token;
  } catch (error) {
    console.error('[CSRF] Token rotation failed:', error);
    throw error;
  }
}

/**
 * ✅ PHASE 2: Get token expiry time
 * Use in CSRFContext for proactive refresh
 */
export function getTokenExpiryTime(maxAge: number = 60 * 60 * 24): number {
  return Date.now() + (maxAge * 1000);
}

/**
 * Delete the CSRF token via API route
 * (Can only be done in Route Handlers or Server Actions in Next.js 16+)
 */
export async function deleteCSRFToken(): Promise<void> {
  // This would need a DELETE endpoint at /api/csrf/generate
  // For now, the cookie will expire naturally after 24 hours
  console.warn('CSRF token deletion must be done via API route in Next.js 16+');
}
